#docker run --rm -itd -v /data:/var/lib/postgresql/data --name pg-fp -e POSTGRES_PASSWORD=postgres postgres:latest
version: '3'
services:
    pg:
        image: postgres:latest
        container_name: ${APP_NAME:?err}-pg
        ports:
            - '5432:5432'
        restart: 'on-failure'
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?err}
            POSTGRES_USER: ${POSTGRES_USER:?err} 
            POSTGRES_DB: ${POSTGRES_DB:?err}
        volumes:
            - './data:/var/lib/postgresql/data'
            - './config/postgresql.conf:/var/lib/postgresql/postgresql.conf'
            - './config/pg_hba.conf:/var/lib/postgresql/pg_hba.conf'
    nginx:
        image: nginx:latest
        container_name: ${APP_NAME:?err}-nginx
        ports:
            - '80:80'
        links:
            - 'pg'
        volumes:
            - './config/nginx.conf:/etc/nginx/nginx.conf'
    scala:
        # image: 'php:7.3-fpm'
        build:
            # context: ./docker
            dockerfile: DockerfileSBT
        stdin_open: true # docker run -i  
        tty: true        # docker run -t 
        # privileged: true           
        container_name: ${APP_NAME:?err}-scala
        ports:
            - '9000:9000'
        links:
            - 'pg'
        volumes:
            - './proyecto-gcs:/app'
